name: 打包并部署

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: 安装Node
        uses: actions/setup-node@v3
        with: 
          node-version: 16.x

      - name: 查看node和npm的版本
        run: |
          node -v
          npm --version

      - name: 读取仓库内容
        uses: actions/checkout@v4

      - name: 安装依赖并打包项目
        run: |
          npm install
          npm run build

      - name: 部署
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: dist